// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

// Protobuf Java Version: 3.25.6
package com.example.grpc;

public interface EmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
